import banner from "@/banner3.jpg";
import { Box, Button, Divider, Grid2, Stack, Typography } from "@mui/material";
import Head from "next/head";
import { COLORS } from "./utils/colors";
import { inter, plus, roboto } from "./utils/fonts";
import { TypeAnimation } from "react-type-animation";
import moment from "moment";
import { ArrowDownward, Mouse } from "@mui/icons-material";
import Experience from "./components/experience";
const calculateExactYearsSince = (): number => {
  const startDate = moment("2022-04-04");
  const currentDate = moment();
  const months = currentDate.diff(startDate, "months", true);
  return parseFloat((months / 12).toFixed(1));
};

export default function Home() {
  const yearsSince = calculateExactYearsSince();

  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Box
          sx={{
            backgroundImage: `url(${banner.src})`,
            height: "100vh",
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat",
            backgroundSize: "cover",
          }}
        >
          <Box
            sx={{
              backgroundColor: "#00000070",
              height: "100%",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <Grid2 container>
              <Grid2
                size={6}
                margin={"auto"}
                className="animate__animated animate__lightSpeedInLeft"
              >
                <Typography
                  color={COLORS.WHITE}
                  fontSize={45}
                  letterSpacing={3}
                  sx={{
                    fontFamily: plus.style,
                    textAlign: "center",
                    lineHeight: 2,
                    fontWeight: 200,
                  }}
                >
                  Hello!
                </Typography>
                <Typography
                  color={COLORS.WHITE}
                  fontSize={50}
                  letterSpacing={3}
                  sx={{
                    fontFamily: roboto.style,
                    fontWeight: 600,
                    wordSpacing: 5,
                    textAlign: "center",
                  }}
                >
                  I'm Kunal Sharma
                </Typography>
                <Box sx={{ textAlign: "center" }}>
                  <TypeAnimation
                    sequence={[
                      "Web Developer",
                      1000,
                      "React Js Developer",
                      1000,
                      "Next Js Developer",
                      1000,
                      "Web Designer",
                      1000,
                      "Frontend Developer",
                      1000,
                    ]}
                    speed={50}
                    style={{
                      fontSize: "40px",
                      color: COLORS.WHITE,
                      textAlign: "center",
                      fontFamily: inter.style.fontFamily,
                      fontWeight: 500,
                      lineHeight: 2,
                    }}
                    repeat={Infinity}
                  />

                  <Typography
                    sx={{
                      color: COLORS.WHITE,
                      fontFamily: inter.style,
                      mt: 1,
                      fontSize: 13,
                    }}
                  >
                    I'm a passionate frontend developer skilled in creating
                    responsive, user-friendly interfaces using React, Next.js,
                    and TypeScript. With a strong foundation in HTML, CSS,
                    JavaScript, and experience in Figma, I bring designs to life
                    with precision and creativity.
                  </Typography>
                  <Box textAlign={"center"} mt={5}>
                    <Mouse htmlColor={COLORS.WHITE} />
                    <Box>
                      <Button
                        endIcon={
                          <ArrowDownward
                            sx={{ fontSize: 14 }}
                            htmlColor={COLORS.WHITE}
                            className="animate__animated animate__shakeY animate__slow animate__infinite	animate__delay-2s"
                          />
                        }
                        href="#section2"
                      >
                        <Typography
                          fontSize={12}
                          sx={{ fontFamily: inter.style, color: COLORS.WHITE }}
                        >
                          Scroll Down
                        </Typography>
                      </Button>
                    </Box>
                  </Box>
                </Box>
              </Grid2>
            </Grid2>
          </Box>
        </Box>
        <div id="section2">
          <Box sx={{ backgroundColor: COLORS.DARKBLUE, pt: 10, pb: 10 }}>
            <Experience experience={yearsSince} />
          </Box>
        </div>
      </Box>
    </>
  );
}
